run:
  tests: false

output:
  formats:
    - format: colored-line-number

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - goimports
    - gosec
    - nilerr
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gosec:
    excludes:
      - G304
