run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-files: []
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout

issues:
  exclude-dirs:
    - vendor
    - .git
    - .github
    
  exclude-rules:
    # Exclude certain linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude specific issues that are acceptable in this project
    - text: "should not use underscores in package names"
      linters:
        - revive

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    # Core Go tools
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality
    - errcheck
    - gosimple
    - revive
    - unconvert
    - unparam
    
    # Security
    - gosec
    
    # Style
    - whitespace
    - misspell
    
    # Bugs
    - bodyclose
    - nilerr
    - rowserrcheck
    - sqlclosecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Struct field alignment is not critical for this project

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/muesli/asciicam

  revive:
    rules:
      - name: exported
        disabled: false

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: true

  gosec:
    excludes:
      - G304  # File path provided as taint input
