name: 'Setup OpenCV'
description: 'Sets up OpenCV for both Ubuntu and macOS'
runs:
  using: "composite"
  steps:
    - name: Install OpenCV on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev pkg-config

    - name: Install OpenCV on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install opencv

    - name: Set environment variables
      shell: bash
      run: |
        PKG_CONFIG_PATH=""
        if [ "${{ runner.os }}" == "macOS" ]; then
          # For Homebrew, OpenCV paths are typically here
          PKG_CONFIG_PATH="/usr/local/opt/opencv/lib/pkgconfig:$PKG_CONFIG_PATH"
        fi
        export PKG_CONFIG_PATH

        echo "Searching for OpenCV pkg-config..."
        if pkg-config --exists opencv4; then
          echo "Found opencv4"
          echo "CGO_CFLAGS=$(pkg-config --cflags opencv4)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$(pkg-config --libs opencv4)" >> $GITHUB_ENV
        elif pkg-config --exists opencv; then
          echo "Found opencv"
          echo "CGO_CFLAGS=$(pkg-config --cflags opencv)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$(pkg-config --libs opencv)" >> $GITHUB_ENV
        else
          echo "Error: OpenCV not found by pkg-config."
          exit 1
        fi
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
