name: 'Setup OpenCV'
description: 'Sets up OpenCV for both Ubuntu and macOS'
runs:
  using: "composite"
  steps:
    - name: Install OpenCV on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev pkg-config
        # Verify installation
        pkg-config --exists opencv4 || pkg-config --exists opencv
        echo "OpenCV installation verified"

    - name: Install OpenCV on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install opencv
        # Verify installation
        brew list opencv
        echo "OpenCV installation verified"

    - name: Set environment variables
      shell: bash
      run: |
        echo "Searching for OpenCV pkg-config..."
        
        # Set PKG_CONFIG_PATH for macOS
        if [ "${{ runner.os }}" == "macOS" ]; then
          # Try both Intel and Apple Silicon Homebrew paths
          for path in "/opt/homebrew/lib/pkgconfig" "/usr/local/lib/pkgconfig" "/usr/local/opt/opencv/lib/pkgconfig"; do
            if [ -d "$path" ]; then
              export PKG_CONFIG_PATH="$path:$PKG_CONFIG_PATH"
              echo "PKG_CONFIG_PATH=$path:$PKG_CONFIG_PATH" >> $GITHUB_ENV
              break
            fi
          done
        fi
        
        # Check for OpenCV
        if pkg-config --exists opencv4; then
          echo "Found opencv4"
          echo "CGO_CFLAGS=$(pkg-config --cflags opencv4)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$(pkg-config --libs opencv4)" >> $GITHUB_ENV
        elif pkg-config --exists opencv; then
          echo "Found opencv"
          echo "CGO_CFLAGS=$(pkg-config --cflags opencv)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$(pkg-config --libs opencv)" >> $GITHUB_ENV
        else
          echo "Error: OpenCV not found by pkg-config."
          echo "Available packages:"
          pkg-config --list-all | grep -i opencv || echo "No OpenCV packages found"
          exit 1
        fi
