name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
      CGO_ENABLED: "1"
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenCV
        run: |
          sudo apt-get update
          # Install complete OpenCV development packages
          sudo apt-get install -y \
            libopencv-dev \
            libopencv-contrib-dev \
            pkg-config \
            build-essential

          # Verify OpenCV installation and get version
          echo "Checking for OpenCV pkg-config files..."
          pkg-config --list-all | grep opencv || echo "No opencv packages found via pkg-config"
          ls /usr/lib/pkgconfig/ | grep opencv || echo "No opencv pkg-config files found"

          # Try both opencv4 and opencv and set environment
          if pkg-config --exists opencv4; then
            opencv_version=$(pkg-config --modversion opencv4)
            echo "Found OpenCV4 version: $opencv_version"
            echo "CGO_CFLAGS=$(pkg-config --cflags opencv4)" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=$(pkg-config --libs opencv4)" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          elif pkg-config --exists opencv; then
            opencv_version=$(pkg-config --modversion opencv)
            echo "Found OpenCV version: $opencv_version"
            echo "CGO_CFLAGS=$(pkg-config --cflags opencv)" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=$(pkg-config --libs opencv)" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          else
            echo "ERROR: No OpenCV pkg-config found"
            echo "Available pkg-config files:"
            ls /usr/lib/pkgconfig/ | grep -i cv || echo "No OpenCV-related files found"
            ls /usr/lib/x86_64-linux-gnu/pkgconfig/ | grep -i cv || echo "No OpenCV-related files found in arch-specific directory"
            exit 1
          fi

      - name: Download Go modules
        run: go mod download

      - name: Test gocv import
        env:
          CGO_ENABLED: ${{ env.CGO_ENABLED }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        run: |
          echo "CGO_CFLAGS: $CGO_CFLAGS"
          echo "CGO_LDFLAGS: $CGO_LDFLAGS"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"

          # Test if gocv can be imported without ArUco issues
          go list -m gocv.io/x/gocv
          echo "Testing basic gocv import..."
          cat > test_gocv.go << 'EOF'
          package main
          import (
              "fmt"
              "gocv.io/x/gocv"
          )
          func main() {
              fmt.Println("gocv version:", gocv.Version())
          }
          EOF
          go run test_gocv.go || echo "gocv test failed - continuing anyway"

      - name: Verify project structure
        run: |
          # Debug: Show current directory structure
          echo "Current directory structure:"
          find . -type f -name "*.go" | head -20
          echo "Directory tree:"
          tree -L 3 || ls -la
          echo "Checking for cmd/asciicam:"
          ls -la cmd/ || echo "cmd directory not found"
          ls -la cmd/asciicam/ || echo "cmd/asciicam directory not found"
          echo "Go mod info:"
          go mod graph | head -5 || echo "go mod graph failed"

      - name: Build
        env:
          CGO_ENABLED: ${{ env.CGO_ENABLED }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        run: |
          echo "Build CGO_CFLAGS: $CGO_CFLAGS"
          echo "Build CGO_LDFLAGS: $CGO_LDFLAGS"

          # Build the main application
          if [ -d "cmd/asciicam" ]; then
            echo "Building from cmd/asciicam..."
            go build -v -o asciicam ./cmd/asciicam
          else
            echo "cmd/asciicam not found, attempting to build from current directory..."
            go build -v -o asciicam .
          fi
          # Verify binary was created
          ls -la asciicam

      - name: Test
        env:
          CGO_ENABLED: ${{ env.CGO_ENABLED }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        run: |
          go test ./...

      - name: Generate coverage report
        env:
          CGO_ENABLED: ${{ env.CGO_ENABLED }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        run: |
          go test -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -html=coverage.out -o coverage.html

    #   - name: Upload coverage reports to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       file: coverage.out
    #       fail_ci_if_error: true
    #       verbose: true
    #     env:
    #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        env:
          CGO_ENABLED: ${{ env.CGO_ENABLED }}
          CGO_CFLAGS: ${{ env.CGO_CFLAGS }}
          CGO_LDFLAGS: ${{ env.CGO_LDFLAGS }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        with:
          version: latest
          args: --out-format=colored-line-number
          only-new-issues: true
