name: Lint Go code

on:
  push:
    branches:
      - main      # remove or adjust if you want every branch
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    # ← enable CGO and tell it where to find OpenCV
    env:
      CGO_ENABLED: "1"
      # Basic OpenCV modules only (no contrib/aruco)
      CGO_CFLAGS: "-I/usr/include/opencv4"
      CGO_LDFLAGS: "-lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_videoio"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install OpenCV dependencies
        run: |
          sudo apt-get update
          # Install minimal OpenCV without any contrib modules
          sudo apt-get install -y libopencv-core-dev libopencv-imgproc-dev libopencv-imgcodecs-dev libopencv-videoio-dev pkg-config
          # DO NOT install: libopencv-contrib-dev (contains ArUco)
          
          # Verify OpenCV installation
          opencv_version=$(pkg-config --modversion opencv4 2>/dev/null || pkg-config --modversion opencv 2>/dev/null || echo "unknown")
          echo "OpenCV version: $opencv_version"

      - name: Download Go modules
        run: go mod download

      # ← optional cache to speed up future runs and quiet the 422 warning
      - name: Cache golangci-lint binary
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/golangci-lint-*
          key: golangci-lint-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: golangci-lint-${{ runner.os }}-

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        env:
          CGO_ENABLED: "1"
          CGO_CFLAGS: "-I/usr/include/opencv4"
          CGO_LDFLAGS: "-lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_videoio"
        with:
          args: --build-tags minimal --out-format=github-actions
